version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  waterkube:
    image: ghcr.io/waterkube/waterkube
    restart: unless-stopped
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - 4000:4000
