apiVersion: batch/v1
kind: Job
metadata:
  name: waterkube-diver-explore
  labels:
    app: waterkube
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: waterkube-diver-explore
          image: ghcr.io/waterkube/waterkube
          env:
            - name: REDIS_URL
              value: 'redis://waterkube:6379/0'
          command:
            - /app/waterkube
            - diver
            - explore
            # - A0
            # - A1
            # ...
      restartPolicy: Never
